@startuml
title __Zustandsdiagramm Parkhaus-Ticket__
state fork1 <<fork>>
state fork2 <<fork>>

[*] --> fork1: Drive in Parkhaus
fork1 --> Ticket_Type: default customer
fork1 --> Leave_Parkhaus: [Is "Firmenkunde" or "Abo"]

Ticket_Type -> fork2
Ticket_Type: entry/ Display Options
Ticket_Type: do/ Customer chooses Type (Time/Tages)
fork2 -> Ticket_Time: default ticket
fork2 -> Ticket_Payment: [Is Tagesticket]

Ticket_Time: entry/ start time
Ticket_Time: exit/ stop time
Ticket_Time -> Ticket_Payment: redirection to payment
Ticket_Payment: entry/ calculate Price
Ticket_Payment: do/ Print Ticket
Ticket_Payment: exit/ Pay Ticket
Ticket_Payment -> Leave_Parkhaus: customer leaves parkhaus
Leave_Parkhaus: entry/ delete instance of ticket_String
Leave_Parkhaus -> [*]

@enduml

//created by everyone - 27.05.21