@startuml
title __Minimierter Automat__
[*] -down-> CF
CF -> CF : a
CF -up> DHG : b
DHG -> DHG : a
DHG -up-> E : b
E -> E : a
E -> E : b
A -up-> CF : a
A -left-> B : b
B -> A : a
B -> E : b
B -left-> [*]

DHG --> [*]
@enduml